extends Node

signal player_direction_changed(direction: float)
signal player_aiming_requested
signal player_aiming_called_off
signal player_exited_ladder
signal player_hurt
signal player_dead
signal player_bounce_up_requested

signal change_level
signal reload_level
